###
GET http://localhost:3000/list

### 
GET http://localhost:3000/list/63ddfc20cbde21ce9d9e0ca0

### 
POST http://localhost:3000/list HTTP/1.1
Content-Type: application/json

{
"fullName": "Alfredo Rebollo",
"city": "Albuquerque", 
"state": "New Mexico",
"task": "Work",
"date": "02/11/2022",
"listToDo": "Tire changes, break check, trailer lights"
}
// RENDER

//UPDATE USER --- NEED ADD
 
// RENDER

###
GET https://cserebolloproject.onrender.com/list 

###
GET https://cserebolloproject.onrender.com/list/63ddfc20cbde21ce9d9e0ca0