###
GET http://localhost:3000/list

### 
GET http://localhost:3000/list/63ddfc20cbde21ce9d9e0ca0

### 
POST http://localhost:3000/list HTTP/1.1
Content-Type: application/json

{
"fullName": "Isabella Rebollo",
"city": "Santa Fe", 
"state": "NM",
"task": "School",
"date": "03/21/2023",
"listToDo": "Reading, colors, numbers"
}
// RENDER

//UPDATE USER --- NEED ADD

### 
PUT http://localhost:3000/list/63f7acf4655de005e3f730ba HTTP/1.1
Content-Type: application/json

{
"fullName": "Alfredo valencia Rebollo",
"city": "Gallup", 
"state": "NM",
"task": "Uncompleted",
"date": "02/20/2023",
"listToDo": "Applications, tax documents, truck repairs"
}

//Delete user task list

###
DELETE http://localhost:3000/list/63f1c4c987bf987bd2e69e30 HTTP/1.1


###
GET https://cserebolloproject.onrender.com/list 

###
GET https://cserebolloproject.onrender.com/list/63ddfc20cbde21ce9d9e0ca0